import { iCliente } from './Cliente';

export interface iContas {
  $id: number;
  CONTA: string;
  VENCIMENTO: string;
  TIPO: string;
  REGISTRO: number;
  Data: string;
  MOVIMENTO: number;
  Doc: string;
  HISTORICO: string;
  TOTAL: number;
  PAGO: number;
  RESTA: number;
  DESCONTO: number;
  DATAPAGAMENTO: string | null;
  PLANODECONTA: number;
  CANCELADO: string;
  TRANSFORMACAO: string;
  COM_NOTA: string;
  EMISSAO_BOLETO: string;
  DATA_BOLETO: string | null;
  HISTORICO2: string;
  CLI_CHQ: number;
  COBRADOR: number;
  ID_CONTA: number;
  ID_SUBCONTA: number;
  NOSSO_NUMERO: string;
  SITUACAO: string;
  REGISTRO_NF: number;
  ID_MCC: number;
  ID_SITUACAO_CHQ: number;
  Usuario: string;
  DATA_HORA: string;
  ID_CTS: number;
  CAIXA: number;
  SPED: string;
  SPED_MODELO: string;
  SPED_SITUACAO: string;
  SPED_VALOR_ICMS: number;
  EMAIL_1: string;
  EMAIL_2: string;
  OBS: string;
  SUBTOTAL: number;
  ACRESCIMO: number;
  ID_VENDEDOR1: number;
  ID_VENDEDOR2: number;
  COMISSAO_VEND1: number;
  COMISSAO_VEND2: number;
  ID_FRETE: number;
  VENCIMENTO_ORIGINAL: string | null;
  CARTAO_ADM: string;
  CARTAO_REDE: string;
  CARTAO_TIPO: string;
  CARTAO_NSU: string;
  CARTAO_CA: string;
  CARTAO_RV: string;
  ID_IMAGEM: number;
  NEGOCIADO: string;
  CODIGO_BARRAS: string;
  CONCILIADO_NEXERA: string;
  LOTE: number;
  ID_Lote_Pgto: number;
  CLIENTE: iCliente;
  'FORNECEDOR@xdata.proxy': string;
  IDCartaoVenda: string | null;
  IDCartaoPgto: string | null;
  IDPagFor: string | null;
  'HistoricoPagamentos_List@xdata.proxy': string;
  'ListaCompetencia@xdata.proxy': string;
}
